<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.reqlint</groupId>
        <artifactId>reqlint</artifactId>
        <version>1.0.3-SNAPSHOT</version>
    </parent>

    <artifactId>reqlint-sandbox</artifactId>
    <packaging>jar</packaging>
    <description>A small project to showcase REQLINT.
        It contains the requirements and implementation for a Token Bucket service.
        The service is tested via cucumber.
        It uses reqlint-maven-plugin to validate the documentation and produce the traceability matrix plus the test report.</description>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
        </dependency>

        <!-- Test dependencies -->
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.platform</groupId>
            <artifactId>junit-platform-suite</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-core</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-java</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-spring</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-junit-platform-engine</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <!-- Uses PlantUml to convert *.puml files into *.eps files -->
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-antrun-plugin</artifactId>
                <executions>
                    <execution>
                        <id>batch-process-files</id>
                        <phase>process-resources</phase>
                        <goals>
                            <goal>run</goal>
                        </goals>
                        <configuration>
                            <target>
                                <apply executable="plantuml" parallel="true">
                                    <arg value="--eps" />
                                    <fileset dir="${project.build.outputDirectory}/documentation" includes="**/*.puml" />
                                </apply>
                            </target>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>com.reqlint</groupId>
                <artifactId>reqlint-maven-plugin</artifactId>
                <configuration>
                    <specificationLatexDocuments>
                        <specificationLatexDocument>${project.build.outputDirectory}/documentation/root.tex</specificationLatexDocument>
                    </specificationLatexDocuments>
                    <traceabilityMatrixOutput>${project.build.outputDirectory}/documentation/traceability/traceability-matrix.tex</traceabilityMatrixOutput>
                    <traceabilityWarningsOutput>${project.build.outputDirectory}/documentation/traceability/traceability-warnings.tex</traceabilityWarningsOutput>
                    <testResultsOutput>${project.build.outputDirectory}/documentation/testresults/testresults-report.tex</testResultsOutput>
                    <testWarningsOutput>${project.build.outputDirectory}/documentation/testresults/testresults-warning.tex</testWarningsOutput>
                </configuration>
                <executions>
                    <!-- Produce the traceability matrix -->
                    <execution>
                        <id>traceability-matrix</id>
                        <!-- To be executed when resources are present in the target folder -->
                        <phase>process-resources</phase>
                        <goals>
                            <goal>traceability-matrix</goal>
                        </goals>
                    </execution>

                    <!-- Produce the test results -->
                    <execution>
                        <id>test-results</id>
                        <!-- To be executed after all integration tests -->
                        <phase>post-integration-test</phase>
                        <goals>
                            <goal>test-results</goal>
                        </goals>
                    </execution>

                    <!-- Compile LaTeX files -->
                    <execution>
                        <id>compile-latex</id>
                        <!-- To be executed after all integration tests, and after test-results -->
                        <phase>post-integration-test</phase>
                        <goals>
                            <goal>compile-latex</goal>
                        </goals>
                        <configuration>
                            <latexTool>lualatex</latexTool> <!-- Depends on your latex distribution -->
                            <bibTool>bibtex</bibTool>
                            <latexDocuments>
                                <latexDocument>${project.build.outputDirectory}/documentation/root.tex</latexDocument>
                                <latexDocument>${project.build.outputDirectory}/documentation/root-testresults.tex</latexDocument>
                                <latexDocument>${project.build.outputDirectory}/documentation/root-traceability.tex</latexDocument>
                            </latexDocuments>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>build-helper-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>attach-pdf-documentation</id>
                        <phase>package</phase>
                        <goals>
                            <goal>attach-artifact</goal>
                        </goals>
                        <configuration>
                            <artifacts>
                                <artifact>
                                    <file>${project.build.outputDirectory}/documentation/root.pdf</file>
                                    <type>pdf</type>
                                    <classifier>spec</classifier>
                                </artifact>
                                <artifact>
                                    <file>${project.build.outputDirectory}/documentation/root-testresults.pdf</file>
                                    <type>pdf</type>
                                    <classifier>test</classifier>
                                </artifact>
                                <artifact>
                                    <file>${project.build.outputDirectory}/documentation/root-traceability.pdf</file>
                                    <type>pdf</type>
                                    <classifier>trace</classifier>
                                </artifact>
                            </artifacts>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>